[build]
publish = "public"
command = "hugo --gc --minify --cleanDestinationDir --baseURL=https://localghost.dev/"

[context.production.environment]
HUGO_VERSION = "0.82.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo  --baseURL=https://localghost.dev/"

[context.split1.environment]
HUGO_VERSION = "0.71.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify -D --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.82.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.71.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://localghost.netlify.com"
  to = "https://localghost.dev"
  status = 301
  force = false
  query = {path = ":path"}